#!/bin/bash
# File @generated by hack/generate-authors.sh. DO NOT EDIT.
# This file lists all contributors to the repository.
# See hack/generate-authors.sh to make modifications.

git log --format='%aN <%aE>' | LC_ALL=C.UTF-8 sort -uf > AUTHORS
